// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CommonResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type DataRespBCTx struct {
	RequestId string `json:"requestId"`
	TxHash    string `json:"txHash"`
}

type DataRespBuildTx struct {
	RequestId  string `json:"requestId"`
	RawMessage string `json:"rawMessage"`
}

type ReqBroadcastTx struct {
	RequestId    string     `json:"requestId"`
	Signatures   [][64]byte `json:"signatures"`
	TxRawMessage string     `json:"txRawMessage"`
}

type ReqBuildTx struct {
	RequestId          string `json:"requestId"`
	FromAddress        string `json:"fromAddress"`
	InputToken         string `json:"inputToken"`
	InputTokenDecimal  int32  `json:"inputTokenDecimal"`
	OutputToken        string `json:"outputToken"`
	OutputTokenDecimal int32  `json:"outputTokenDecimal"`
	Slippage           string `json:"slippage"`
	Amount             string `json:"amount"`
	Fee                uint64 `json:"fee"`
}

type RespBroadcastTx struct {
	CommonResponse
	Data DataRespBCTx `json:"data"`
}

type RespBuildTx struct {
	CommonResponse
	Data DataRespBuildTx `json:"data"`
}
